### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by bernhardschmidt** [rdegges/pyst2#37]
In 55cc2a09b39914bdf96b8f947d96becab78aed17 the string "UNLICENSE" was added to the licenses. 

It is totally unclear to me which license this project is using. Can you clarify this? With an unclear license it is impossible to package this in Debian.

**Comment by ar13pit** [comment]
The documentation for UNLICENSE can be found here:
https://choosealicense.com/licenses/unlicense/

Although I plan to change it.

**Comment by rdegges** [comment]
Yes. Feel free to change. Just fyi: I chose unlicense because it is public domain. That means anyone can use it for any purpose in any way they want with absolutely  no restrictions.

**Comment by ar13pit** [comment]
@rdegges As I remember with GNU GPLv3 too anyone can use it for any purpose but only with the condition that their modified source code of the library must be shared. I feel this will lead to better development of the library.

Correct me if I am wrong.

**Comment by rdegges** [comment]
The only issue I have with GPL licenses is that it makes it hard for companies to use this software. That's because a lot of companies want to package it up themselves in their paid, proprietary apps, and you can't do that using GPL unless you also release all your company source code. That's a big issue for adoption IMO. Public domain licenses are the most effective and permissive ones that exist, which is why I'm a fan of it.

If you really wanna change it to something more 'mainstream', the MIT license is the next best option as it has the same rights, but also includes some more 'business' wording.

FWIW: https://www.rdegges.com/2016/i-dont-give-a-shit-about-licensing/

**Comment by ar13pit** [comment]
Alright. MIT License it is then.

Nice article by the way.
